server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: http://jiangzh:jiangzh123@localhost:8761/eureka/

spring:
  security:
    user:
      name: jiangzh
      password: jiangzh123
      roles: SUPERUSER

logging:
  config: classpath:logback.xml

