server:
  port: 7201

eureka:
  client:
    service-url:
      defaultZone: http://jiangzh:jiangzh123@localhost:8761/eureka/

spring:
  application:
    name: hello-service-consumer

#全局配置 最大重试次数
ribbon:
  MaxAutoRetries : 3

#单个服务配置 最大重试次数
hello-service-provider:
  ribbon:
    MaxAutoRetries : 3

feign:
  #开启hystrix
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  compression:
    request:
      #求和响应GZIP压缩支持
      enabled: true
      #支持压缩的mime types
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048 #开启压缩的最大size
      #开启压缩
    response:
      enabled: true

#配置日志
logging:
  config: classpath:logback.xml

